'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.Welcome

    Partial Public Class Settings

        '''<summary>
        '''plText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plText As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''teText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents teText As Global.DotNetNuke.UI.UserControls.TextEditor

        '''<summary>
        '''plViews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plViews As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtViews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtViews As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''vldViewsRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldViewsRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vldViewsCompare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldViewsCompare As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plViewsSessionBased control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plViewsSessionBased As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkViewsSessionBased control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkViewsSessionBased As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plDisplayHide control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDisplayHide As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkDisplayHide control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDisplayHide As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideText As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtHideText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHideText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plDisplayKeepHidden control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDisplayKeepHidden As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlDisplayKeepHidden control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDisplayKeepHidden As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plKeepHiddenText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plKeepHiddenText As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtKeepHiddenText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtKeepHiddenText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plVersion As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtVersion As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''vldVersionRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldVersionRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vldVersionCompare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldVersionCompare As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plWhenHiddenText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plWhenHiddenText As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''teWhenHiddenText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents teWhenHiddenText As Global.DotNetNuke.UI.UserControls.TextEditor

        '''<summary>
        '''plUnhideText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUnhideText As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtUnhideText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUnhideText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plIpAddressRegEx control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIpAddressRegEx As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtIpAddressRegEx control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIpAddressRegEx As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
